/*
 * Copyright 2026 Google LLC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
  `java-library`
  `java-test-fixtures`
  kotlin("jvm")
}

dependencies {
  api(libs.androidx.ink.brush.jvm)
  api(libs.androidx.ink.storage.jvm)

  implementation(libs.google.genai)
  implementation(libs.kotlinx.coroutines.core)

  // Required at compile time for package-info.java (@SuppressPackageLocation) so ChatResumer
  // can reside in com.google.genai to access package-private SDK internals.
  compileOnly(libs.errorprone.annotations)

  testImplementation(libs.junit)
  testImplementation(libs.truth)
  testImplementation(libs.kotlinx.coroutines.test)

  testFixturesImplementation(libs.google.genai)
}

// Copies prompt.md generated by :aibd:prompt into the exact package directory path expected
// by Harness.loadSystemPrompt() on the classpath (/com/example/cahier/aibd/prompt/prompt.md).
val copyPromptResource by
  tasks.registering(Copy::class) {
    from(project(":aibd:prompt").tasks.named("generatePrompt"))
    into(layout.buildDirectory.dir("generated/resources/com/example/cahier/aibd/prompt"))
  }

sourceSets { main { resources { srcDir(layout.buildDirectory.dir("generated/resources")) } } }

tasks.named("processResources") { dependsOn(copyPromptResource) }
